export const ACTION_TYPES = {
  INITIALISE_CATEGORIES: "INITIALISE_CATEGORIES",
  INITIALISE_PRODUCTS: "INITIALISE_PRODUCTS",

  CATEGORY: "CATEGORY",
  RATINGS: "RATINGS",
  SORTBY: "SORTBY",
  PRICE_RANGE: "PRICE_RANGE",
  INPUT_SEARCH: "INPUT_SEARCH",

  CLEAR_FILTERS: "CLEAR_FILTERS",
};
