export const ACTION_TYPES = {
  INITIALISE_CATEGORIES: "INITIALISE_CATEGORIES",
  INITIALISE_PRODUCTS: "INITIALISE_PRODUCTS",
  INITIALISE_CART: "INITIALISE_CART",
  INITIALISE_WISHLIST: "INITIALISE_WISHLIST",
  INITIALISE_ADDRESS: "INITIALISE_ADDRESS",

  CATEGORY: "CATEGORY",
  RATINGS: "RATINGS",
  SORTBY: "SORTBY",
  PRICE_RANGE: "PRICE_RANGE",
  INPUT_SEARCH: "INPUT_SEARCH",
  CLEAR_FILTERS: "CLEAR_FILTERS",

  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  UPDATE_CART: "UPDATE_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",

  SET_JWT_TOKEN: "SET_JWT_TOKEN",
  SET_USER: "SET_USER",
  LOG_OUT: "LOG_OUT",

  ADD_ADDRESS: "ADD_ADDRESS",
  REMOVE_ADDRESS: "REMOVE_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  SET_DELIVERY_ADDRESS: "SET_DELIVERY_ADDRESS",

  SET_ORDER_SUMMARY_PRICE: "SET_ORDER_SUMMARY_PRICE",
  SET_ORDER_SUMMARY_ITEMS: "SET_ORDER_SUMMARY_ITEMS",
  SET_ORDER_SUMMARY_ADDRESS: "SET_ORDER_SUMMARY_ADDRESS",
};
